apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
    name: where-for-dinner-search-proc
spec:
    serviceAccountName: default
    packageRef:
        refName: where-for-dinner-search-proc.my-apps.tap
        versionSelection:
            constraints: 20240430055610.0.0+build.6aff574
    values:
        - secretRef:
            name: where-for-dinner-search-proc
