apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20240430055334.0.0+build.6aff574
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20240430055334.0.0+build.6aff574
  releaseNotes: |
    Release v20240430055334.0.0+build.6aff574 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tap-ci/ci-pipeline/apps-29-04-2024-22-39-27-429164758/where-for-dinner-my-apps-bundle@sha256:8c69d5b867578907f495e3dc7a9cef8492fc76d2e79470e196b13e689905e0b2
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

